---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - image: nextcloud:latest
        name: nextcloud
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/html"
          name: var-www-html
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: var-www-html
        persistentVolumeClaim:
          claimName: nextcloud-pvc
